#! /bin/bash

export AWS_PROFILE=default

# Seperate
#aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths "/samples/*"

#aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths "/5ks/*"
#aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths "/cabin/*"
#aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths "/clouds/*"
#aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths "/swa/*"
#aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths "/turkeys/*"
#aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths "/twells/*"

# Do Together
 aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths /index.html /about.html /fav2.html
 aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths "/assets/*"

